version: 0.2
phases:
  commands:
      - echo "Installing Java 21..."
      - amazon-linux-extras enable corretto21
      - yum install -y java-21-amazon-corretto-devel
      - java -version
      - echo "Installing Maven dependencies..."
      - mvn install -DskipTests
  build:
    commands:
      - echo Packaging JAR file...
      - mvn clean package
  post_build:
    commands:
      - echo Build complete.
artifacts:
  files:
    - target/demo.jar
  discard-paths: yes