version: 0.2
phases:
  commands:
    - echo "Installing dependencies..."
    - mvn install -DskipTests
  build:
    commands:
      - echo Packaging JAR file...
      - mvn clean package
  post_build:
    commands:
      - echo Build complete.
artifacts:
  files:
    - target/demo.jar
  discard-paths: yes